---
# .github/workflows/ci-seed.yaml
name: CI Seed Workflow
on:
  workflow_dispatch:
    inputs:
      target_workflow:
        description: 'The filename of the target workflow to run (e.g. test_course_01_creating_postgres_db.yaml)'
        required: true
      target_ref:
        description: 'The Git ref (e.g. feature branch) that contains the workflow'
        required: true
permissions:
  actions: write  # Required to dispatch another workflow
jobs:
  dispatch:
    name: Dispatch ${{ inputs.target_workflow }} on ${{ inputs.target_ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          echo "Dispatching '${{ inputs.target_workflow }}' on ref '${{ inputs.target_ref }}'"
          gh workflow run "${{ inputs.target_workflow }}" --ref "${{ inputs.target_ref }}"
